name: seyahat
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  http: ^0.13.0
  shared_preferences: ^2.0.13  # Ensure it's up-to-date
  flutter:
    sdk: flutter
  multi_select_flutter: ^4.0.0
  image_picker: ^0.8.4+4
  flutter_localizations:
    sdk: flutter
  intl: 0.19.0
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.4
  firebase_messaging: ^15.1.3

  cupertino_icons: ^1.0.8
  emoji_picker_flutter: ^2.0.0  # Update to the latest version




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Add your assets here
  assets:
    - assets/country.json
    - assets/seyahat.png
    - assets/smallplane.png
    - assets/mountain.png
    - assets/flower.png
    - assets/user.png
    - assets/guide.png
    - assets/success.png
    - assets/view.png
    - assets/explore.png
    - assets/user.png

  # You can add more assets like:
  # - assets/image1.png
  # - assets/image2.jpg

  # To add custom fonts, you can uncomment and configure this section:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
